name: rvmre

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ReVanced/revanced-manager
        ref: compose-dev
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease -Psign
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SK }}
        alias: ${{ secrets.AS }}
        keyStorePassword: ${{ secrets.KSP }}
        keyPassword: ${{ secrets.KP }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
